# Generated by Django 5.1.1 on 2024-09-13 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandePret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_demande', models.DecimalField(decimal_places=2, max_digits=15)),
                ('duree', models.PositiveIntegerField(help_text='Durée en mois')),
                ('taux_interet', models.DecimalField(decimal_places=2, help_text="Taux d'intérêt annuel en pourcentage", max_digits=5)),
                ('motif', models.TextField()),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuvé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20)),
                ('paiement_effectue', models.BooleanField(default=False)),
                ('commentaires_banque', models.TextField(blank=True, default="Votre demende est en cours d'examen...", null=True)),
            ],
            options={
                'verbose_name': 'Demande de Prêt',
                'verbose_name_plural': 'Demandes de Prêts',
            },
        ),
        migrations.CreateModel(
            name='CrediteCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte', models.CharField(max_length=34)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(default='EUR', max_length=3)),
                ('reference_transaction', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('emetteur', models.CharField(blank=True, max_length=255, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crédit de Compte',
                'verbose_name_plural': 'Crédits de Comptes',
            },
        ),
        migrations.CreateModel(
            name='DemandeRetrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_retrait', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('no_reply', models.BooleanField(default=True)),
                ('recipients', models.ManyToManyField(related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='message_attachments/')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_files', to='banque_app.message')),
            ],
        ),
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_bool', models.BooleanField(default=False)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=500, null=True)),
                ('demande_pret', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banque_app.demandepret')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Succès'), ('FAILURE', 'Échec'), ('PENDING', 'En attente')], max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=500, null=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=500, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('user_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='banque_app.userpayment')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birth_place', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Homme'), ('female', 'Femme'), ('other', 'Autre')], max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('income_source', models.CharField(blank=True, max_length=255, null=True)),
                ('profession', models.CharField(choices=[('employed', 'Employé'), ('self-employed', 'Entrepreneur'), ('retired', 'Retraité'), ('other', 'Autre')], max_length=20)),
                ('terms', models.BooleanField(default=False)),
                ('consent', models.BooleanField(default=False)),
                ('confirmation', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('Vérifier', 'Vérifier'), ('Non vérifier', 'Non vérifier'), ('En attente de vérification', 'En attente de vérification'), ('En cours de vérification', 'En cours de vérification')], default='Non vérifier', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userpayment',
            name='app_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banque_app.userprofile'),
        ),
        migrations.CreateModel(
            name='Identite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=34)),
                ('id_photo', models.ImageField(upload_to='user_photos/')),
                ('cnss', models.CharField(max_length=100, null=True)),
                ('number_carte_passport', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banque_app.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='demandepret',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_pret', to='banque_app.userprofile'),
        ),
        migrations.CreateModel(
            name='CompteBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte', models.CharField(max_length=20, unique=True)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banque_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Virement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.IntegerField(choices=[(1, 'Initié'), (2, 'En cours'), (3, 'Terminé')], default=1)),
                ('message_admin', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Virement',
                'verbose_name_plural': 'Virements',
            },
        ),
    ]
