# Generated by Django 5.1.1 on 2024-09-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banque_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recipients',
            field=models.ManyToManyField(related_name='received_messages', to='banque_app.userprofile'),
        ),
    ]
