# Generated by Django 5.1.1 on 2024-09-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banque_app', '0004_remove_creditecompte_description_af_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditecompte',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditecompte',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditecompte',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditecompte',
            name='description_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditecompte',
            name='emetteur_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='creditecompte',
            name='emetteur_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='creditecompte',
            name='emetteur_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='creditecompte',
            name='emetteur_it',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='demandepret',
            name='commentaires_banque_en',
            field=models.TextField(blank=True, default="Votre demende est en cours d'examen...", null=True),
        ),
        migrations.AddField(
            model_name='demandepret',
            name='commentaires_banque_es',
            field=models.TextField(blank=True, default="Votre demende est en cours d'examen...", null=True),
        ),
        migrations.AddField(
            model_name='demandepret',
            name='commentaires_banque_fr',
            field=models.TextField(blank=True, default="Votre demende est en cours d'examen...", null=True),
        ),
        migrations.AddField(
            model_name='demandepret',
            name='commentaires_banque_it',
            field=models.TextField(blank=True, default="Votre demende est en cours d'examen...", null=True),
        ),
        migrations.AddField(
            model_name='demandepret',
            name='motif_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='demandepret',
            name='motif_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='demandepret',
            name='motif_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='demandepret',
            name='motif_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='identite',
            name='cnss_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='identite',
            name='cnss_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='identite',
            name='cnss_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='identite',
            name='cnss_it',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='identite',
            name='iban_en',
            field=models.CharField(max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='identite',
            name='iban_es',
            field=models.CharField(max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='identite',
            name='iban_fr',
            field=models.CharField(max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='identite',
            name='iban_it',
            field=models.CharField(max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='content_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='content_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='content_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='subject_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='subject_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='subject_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='subject_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_place_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_place_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_place_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_place_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='income_source_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='income_source_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='income_source_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='income_source_it',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nationality_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nationality_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nationality_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nationality_it',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profession_en',
            field=models.CharField(choices=[('employed', 'Employé'), ('self-employed', 'Entrepreneur'), ('retired', 'Retraité'), ('other', 'Autre')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profession_es',
            field=models.CharField(choices=[('employed', 'Employé'), ('self-employed', 'Entrepreneur'), ('retired', 'Retraité'), ('other', 'Autre')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profession_fr',
            field=models.CharField(choices=[('employed', 'Employé'), ('self-employed', 'Entrepreneur'), ('retired', 'Retraité'), ('other', 'Autre')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profession_it',
            field=models.CharField(choices=[('employed', 'Employé'), ('self-employed', 'Entrepreneur'), ('retired', 'Retraité'), ('other', 'Autre')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='virement',
            name='message_admin_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virement',
            name='message_admin_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virement',
            name='message_admin_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virement',
            name='message_admin_it',
            field=models.TextField(blank=True, null=True),
        ),
    ]
